{{- if .Values.jellyfin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: {{ .Release.Name }}-jellyfin
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  type: {{ .Values.jellyfin.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.jellyfin.service.port | default 8096 }}
      targetPort: http
      protocol: TCP
      name: http
{{ if (and (eq .Values.jellyfin.service.type "NodePort") (not (empty .Values.jellyfin.service.nodePort))) }}
      nodePort: {{.Values.jellyfin.service.nodePort}}
{{ end }}
  selector:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: {{ .Release.Name }}-jellyfin
{{- end }}
