{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    {{- .Values.deployment.strategy | toYaml | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- if and .Values.velero.enabled (or .Values.persistence.enabled .Values.persistence.backup.enabled) }}
      annotations:
        backup.velero.io/backup-volumes: {{ if .Values.persistence.backup.enabled }}backup{{ else }}data{{ end }}
      {{- end }}
      {{- with .Values.podAnnotations }}
      {{- if not (and $.Values.velero.enabled (or $.Values.persistence.enabled $.Values.persistence.backup.enabled)) }}
      annotations:
      {{- end }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: nextcloud
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name | default (printf "%s-nextcloud" .Release.Name) }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-nextcloud" .Release.Name) }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if .Values.persistence.backup.enabled }}
        - name: backup
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.backup.existingClaim | default (printf "%s-backup" .Release.Name) }}
        {{- end }}
        {{- if .Values.persistence.additionalVolumes }}
          {{- .Values.persistence.additionalVolumes | toYaml | nindent 8}}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /var/www/html
              name: data
          {{- if .Values.persistence.backup.enabled }}
            - mountPath: /var/www/html/data/backups
              name: backup
          {{- end }}
          {{- if .Values.persistence.additionalMounts }}
            {{- .Values.persistence.additionalMounts | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            {{- if eq .Values.postgres.mode "standalone" }}
            # Standalone PostgreSQL mode
            - name: POSTGRES_HOST
              value: {{ .Release.Name }}-nextcloud-postgresql
            - name: POSTGRES_DB
              value: {{ .Values.postgres.username }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "nextcloud.postgresql.secretName" . }}
                  key: password
            {{- else if eq .Values.postgres.mode "cluster" }}
            # CloudNativePG cluster mode
            - name: POSTGRES_HOST
              value: {{ include "nextcloud.postgresql.host" . }}
            - name: POSTGRES_DB
              value: {{ include "nextcloud.postgresql.database" . }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-nextcloud-db-app" .Release.Name }}
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "nextcloud.postgresql.secretName" . }}
                  key: password
            {{- else if eq .Values.postgres.mode "external" }}
            # External PostgreSQL mode
            - name: POSTGRES_HOST
              value: {{ .Values.postgres.external.host }}:{{ .Values.postgres.external.port | default 5432 }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.username }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "nextcloud.postgresql.secretName" . }}
                  key: password
            {{- end }}
            {{- if and (ne .Values.dragonfly.mode "disabled") (ne .Values.dragonfly.mode "") }}
            # DragonflyDB/Redis connection for caching
            - name: REDIS_HOST
              value: {{ include "nextcloud.dragonfly.host" . }}
            - name: REDIS_HOST_PORT
              value: {{ include "nextcloud.dragonfly.port" . | quote }}
            - name: REDIS_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "nextcloud.dragonfly.secretName" . }}
                  key: {{ include "nextcloud.dragonfly.passwordKey" . }}
            {{- end }}
            {{- range $k,$v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
