{{- if .Values.image.autoupdate.enabled }}
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.imageUpdater.namespace | default "argocd" }}
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
spec:
  namespace: {{ .Values.imageUpdater.argocdNamespace | default "argocd" }}
  applicationRefs:
    - namePattern: {{ .Values.imageUpdater.applicationName | default .Release.Name | quote }}
      images:
        - alias: {{ .Values.imageUpdater.imageAlias | default .Release.Name | quote }}
          imageName: {{ .Values.image.repository }}{{ if .Values.image.tag }}:{{ .Values.image.tag }}{{ end }}
          {{- if or .Values.image.autoupdate.strategy .Values.image.autoupdate.allowTags .Values.image.autoupdate.ignoreTags .Values.image.autoupdate.pullSecret .Values.imageUpdater.forceUpdate .Values.image.autoupdate.platforms }}
          commonUpdateSettings:
            {{- if .Values.image.autoupdate.strategy }}
            updateStrategy: {{ .Values.image.autoupdate.strategy }}
            {{- end }}
            {{- if .Values.imageUpdater.forceUpdate }}
            forceUpdate: {{ .Values.imageUpdater.forceUpdate }}
            {{- end }}
            {{- if .Values.image.autoupdate.allowTags }}
            allowTags: {{ .Values.image.autoupdate.allowTags | quote }}
            {{- end }}
            {{- if .Values.image.autoupdate.ignoreTags }}
            ignoreTags:
              {{- if kindIs "string" .Values.image.autoupdate.ignoreTags }}
              - {{ .Values.image.autoupdate.ignoreTags | quote }}
              {{- else }}
              {{- toYaml .Values.image.autoupdate.ignoreTags | nindent 14 }}
              {{- end }}
            {{- end }}
            {{- if .Values.image.autoupdate.pullSecret }}
            pullSecret: {{ .Values.image.autoupdate.pullSecret | quote }}
            {{- end }}
            {{- if .Values.image.autoupdate.platforms }}
            platforms:
              {{- toYaml .Values.image.autoupdate.platforms | nindent 14 }}
            {{- end }}
          {{- end }}
          {{- if or .Values.imageUpdater.helm .Values.imageUpdater.kustomize }}
          manifestTargets:
            {{- if .Values.imageUpdater.helm }}
            helm:
              {{- toYaml .Values.imageUpdater.helm | nindent 14 }}
            {{- end }}
            {{- if .Values.imageUpdater.kustomize }}
            kustomize:
              {{- toYaml .Values.imageUpdater.kustomize | nindent 14 }}
            {{- end }}
          {{- end }}
  {{- if .Values.imageUpdater.writeBackConfig }}
  writeBackConfig:
    {{- toYaml .Values.imageUpdater.writeBackConfig | nindent 4 }}
  {{- end }}
{{- end }}
