{{- if .Values.emby.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-emby
  labels:
    app.kubernetes.io/name: emby
    app.kubernetes.io/instance: {{ .Release.Name }}-emby
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  {{- if not .Values.emby.autoscaling.enabled }}
  replicas: {{ .Values.emby.replicaCount }}
  {{- end }}
  strategy:
    {{- .Values.emby.deployment.strategy | toYaml | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: emby
      app.kubernetes.io/instance: {{ .Release.Name }}-emby
  template:
    metadata:
      {{- if and $.Values.velero.enabled (or .Values.emby.persistence.enabled .Values.emby.persistence.backup.enabled) }}
      annotations:
        backup.velero.io/backup-volumes: {{ if .Values.emby.persistence.backup.enabled }}backup{{ else }}config{{ end }}
      {{- end }}
      {{- with .Values.emby.podAnnotations }}
      {{- if not (and $.Values.velero.enabled (or $.Values.emby.persistence.enabled $.Values.emby.persistence.backup.enabled)) }}
      annotations:
      {{- end }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: emby
        app.kubernetes.io/instance: {{ .Release.Name }}-emby
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/part-of: {{ .Release.Name | quote }}
    spec:
      {{- with .Values.emby.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.emby.serviceAccount.name | default (printf "%s-emby" .Release.Name) }}
      securityContext:
        {{- toYaml .Values.emby.podSecurityContext | nindent 8 }}
      {{- if .Values.emby.initContainers }}
      initContainers:
        {{- toYaml .Values.emby.initContainers | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          {{- if .Values.emby.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.emby.persistence.existingClaim | default (printf "%s-emby" .Release.Name) }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if .Values.emby.persistence.cache.enabled }}
        - name: cache
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "{{ .Values.emby.persistence.cache.accessMode }}" ]
                {{- if .Values.emby.persistence.cache.storageClass }}
                storageClassName: {{ .Values.emby.persistence.cache.storageClass | quote }}
                {{- end }}
                resources:
                  requests:
                    storage: {{ .Values.emby.persistence.cache.size }}
        {{- end }}
        {{- if .Values.emby.persistence.transcode.enabled }}
        - name: transcode
          {{- if eq .Values.emby.persistence.transcode.type "memory" }}
          emptyDir:
            medium: Memory
            {{- if .Values.emby.persistence.transcode.memory.sizeLimit }}
            sizeLimit: {{ .Values.emby.persistence.transcode.memory.sizeLimit }}
            {{- end }}
          {{- else if eq .Values.emby.persistence.transcode.type "disk" }}
          {{- if .Values.emby.persistence.transcode.disk.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.emby.persistence.transcode.disk.existingClaim }}
          {{- else }}
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "{{ .Values.emby.persistence.transcode.disk.accessMode }}" ]
                {{- if .Values.emby.persistence.transcode.disk.storageClass }}
                storageClassName: {{ .Values.emby.persistence.transcode.disk.storageClass | quote }}
                {{- end }}
                resources:
                  requests:
                    storage: {{ .Values.emby.persistence.transcode.disk.size }}
          {{- end }}
          {{- else }}
          {{- fail "emby.persistence.transcode.type must be either 'memory' or 'disk'" }}
          {{- end }}
        {{- end }}
        - name: media
          {{- if and .Values.media.enabled .Values.emby.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.media.existingClaim }}{{ .Values.media.existingClaim }}{{- else }}{{ .Release.Name }}-media{{- end }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if .Values.emby.persistence.backup.enabled }}
        - name: backup
          persistentVolumeClaim:
            claimName: {{ .Values.emby.persistence.backup.existingClaim | default (printf "%s-emby-backup" .Release.Name) }}
        {{- end }}
        {{- if .Values.emby.persistence.additionalVolumes }}
          {{- .Values.emby.persistence.additionalVolumes | toYaml | nindent 8}}
        {{- end }}
      containers:
        - name: emby
          securityContext:
            {{- toYaml .Values.emby.securityContext | nindent 12 }}
          image: "{{ .Values.emby.image.repository }}:{{ .Values.emby.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.emby.image.pullPolicy }}
          volumeMounts:
            - mountPath: /config
              name: config
            {{- if .Values.emby.persistence.backup.enabled }}
            - mountPath: /config/backups
              name: backup
            {{- end }}
            {{- if .Values.emby.persistence.cache.enabled }}
            - mountPath: /config/cache
              name: cache
            {{- end }}
            {{- if .Values.emby.persistence.transcode.enabled }}
            - mountPath: /config/transcoding-temp
              name: transcode
            {{- end }}
          {{- if and .Values.media.enabled .Values.sonarr.enabled .Values.sonarr.persistence.enabled .Values.emby.persistence.enabled }}
            - mountPath: "/media/{{ .Values.media.paths.tv }}"
              name: media
              subPath: {{ .Values.media.paths.tv }}
          {{- end }}
          {{- if and .Values.media.enabled .Values.radarr.enabled .Values.radarr.persistence.enabled .Values.emby.persistence.enabled }}
            - mountPath: "/media/{{ .Values.media.paths.movies }}"
              name: media
              subPath: {{ .Values.media.paths.movies }}
          {{- end }}
          {{- if and .Values.media.enabled .Values.lidarr.enabled .Values.lidarr.persistence.enabled .Values.emby.persistence.enabled }}
            - mountPath: "/media/{{ .Values.media.paths.music }}"
              name: media
              subPath: {{ .Values.media.paths.music }}
          {{- end }}
          {{- if .Values.emby.persistence.additionalMounts }}
            {{- .Values.emby.persistence.additionalMounts | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8096
              protocol: TCP
          env:
            {{- range $k,$v := .Values.emby.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.emby.resources | nindent 12 }}
      {{- if .Values.emby.runtimeClassName }}
      runtimeClassName: {{ .Values.emby.runtimeClassName | quote }}
      {{- end }}
      {{- with .Values.emby.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.emby.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.emby.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
