{{- if .Values.emby.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-emby
  labels:
    app.kubernetes.io/name: emby
    app.kubernetes.io/instance: {{ .Release.Name }}-emby
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  {{- if not .Values.emby.autoscaling.enabled }}
  replicas: {{ .Values.emby.replicaCount }}
  {{- end }}
  strategy:
    {{- .Values.emby.deployment.strategy | toYaml | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: emby
      app.kubernetes.io/instance: {{ .Release.Name }}-emby
  template:
    metadata:
      {{- with .Values.emby.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: emby
        app.kubernetes.io/instance: {{ .Release.Name }}-emby
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/part-of: {{ .Release.Name | quote }}
    spec:
      {{- with .Values.emby.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.emby.serviceAccount.name | default (printf "%s-emby" .Release.Name) }}
      securityContext:
        {{- toYaml .Values.emby.podSecurityContext | nindent 8 }}
      {{- if .Values.emby.initContainers }}
      initContainers:
        {{- toYaml .Values.emby.initContainers | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          {{- if .Values.emby.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.emby.persistence.existingClaim | default (printf "%s-emby" .Release.Name) }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if .Values.emby.persistence.cache.enabled }}
        - name: cache
          emptyDir:
            {{- if .Values.emby.persistence.cache.size }}
            sizeLimit: {{ .Values.emby.persistence.cache.size }}
            {{- end }}
        {{- end }}
        - name: media
          {{- if and .Values.media.enabled .Values.emby.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.media.existingClaim }}{{ .Values.media.existingClaim }}{{- else }}{{ .Release.Name }}-media{{- end }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if .Values.emby.persistence.additionalVolumes }}
          {{- .Values.emby.persistence.additionalVolumes | toYaml | nindent 8}}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.emby.securityContext | nindent 12 }}
          image: "{{ .Values.emby.image.repository }}:{{ .Values.emby.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.emby.image.pullPolicy }}
          entrypoint:
            - "/bin/sh"
            - "-c"
            - echo IyEvYmluL2FzaAoKTlZJRElBX1ZFUlNJT049JChscyAvdXNyL2xpYjY0L2xpYmN1ZGEuc28uKiB8IHNlZCAtRSAncy8uKmxpYmN1ZGFcLnNvKFwuMXxcLik/Ly8nIHwgdHIgLWQgXFxuKQoKY2QgL3Vzci9saWI2NCAmJiBcCmxuIC1zIGxpYmN1ZGEuc28uJHtOVklESUFfVkVSU0lPTn0gbGliY3VkYS5zby4xICYmIFwKbG4gLXMgbGlibnZpZGlhLW9wdGljYWxmbG93LnNvLiR7TlZJRElBX1ZFUlNJT059IGxpYm52aWRpYS1vcHRpY2FsZmxvdy5zby4xICYmIFwKbG4gLXMgbGlibnZpZGlhLWVuY29kZS5zby4ke05WSURJQV9WRVJTSU9OfSBsaWJudmlkaWEtZW5jb2RlLnNvLjEgJiYgXApsbiAtcyBsaWJudmN1dmlkLnNvLiR7TlZJRElBX1ZFUlNJT059IGxpYm52Y3V2aWQuc28uMSAmJiBcCmxuIC1zIGxpYm52aWRpYS1jZmcuc28uJHtOVklESUFfVkVSU0lPTn0gbGlibnZpZGlhLWNmZy5zby4xICYmIFwKbG4gLXMgbGlidmRwYXVfbnZpZGlhLnNvLiR7TlZJRElBX1ZFUlNJT059IGxpYnZkcGF1X252aWRpYS5zby4xCgpsbiAtcyBsaWJudmlkaWEtZW5jb2RlLnNvLjEgbGlibnZpZGlhLWVuY29kZS5zbyAmJiBcCmxuIC1zIGxpYm52Y3V2aWQuc28uMSBsaWJudmN1dmlkLnNvICYmIFwKbG4gLXMgbGlibnZpZGlhLWNmZy5zby4xIGxpYm52aWRpYS1jZmcuc28KbG4gLXMgbGlidmRwYXVfbnZpZGlhLnNvLjEgbGlidmRwYXVfbnZpZGlhLnNvCgovaW5pdCAkQA==
              | base64 -d > /nvidia-fix-init && chmod +x /nvidia-fix-init && /nvidia-fix-init
              $$@
          volumeMounts:
            - mountPath: /config
              name: config
            {{- if .Values.emby.persistence.cache.enabled }}
            - mountPath: /config/cache
              name: cache
            {{- end }}
          {{- if and .Values.media.enabled .Values.sonarr.enabled .Values.sonarr.persistence.enabled .Values.emby.persistence.enabled }}
            - mountPath: "/media/{{ .Values.media.paths.tv }}"
              name: media
              subPath: {{ .Values.media.paths.tv }}
          {{- end }}
          {{- if and .Values.media.enabled .Values.radarr.enabled .Values.radarr.persistence.enabled .Values.emby.persistence.enabled }}
            - mountPath: "/media/{{ .Values.media.paths.movies }}"
              name: media
              subPath: {{ .Values.media.paths.movies }}
          {{- end }}
          {{- if and .Values.media.enabled .Values.lidarr.enabled .Values.lidarr.persistence.enabled .Values.emby.persistence.enabled }}
            - mountPath: "/media/{{ .Values.media.paths.music }}"
              name: media
              subPath: {{ .Values.media.paths.music }}
          {{- end }}
          {{- if .Values.emby.persistence.additionalMounts }}
            {{- .Values.emby.persistence.additionalMounts | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8096
              protocol: TCP
          env:
            {{- range $k,$v := .Values.emby.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.emby.resources | nindent 12 }}
      {{- if .Values.emby.runtimeClassName }}
      runtimeClassName: {{ .Values.emby.runtimeClassName | quote }}
      {{- end }}
      {{- with .Values.emby.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.emby.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.emby.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
