{{- if and (not .Values.openclaw.gatewayToken.secretName) .Values.openclaw.gatewayToken.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openclaw.fullname" . }}-gateway-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENCLAW_GATEWAY_TOKEN: {{ .Values.openclaw.gatewayToken.value | quote }}
{{- end }}
