name: homepage
maintainers:
  - name: raulpatel
    url: https://raulpatel.com
apiVersion: v2
appVersion: v0.9.15
version: 1.2.0
description: Homepage Dashboard Helm Chart with Kubernetes Service Discovery
type: application
home: https://github.com/FeLiNa22/homeserver/tree/main/charts/homepage
icon: https://raulpatel.com/images/raul.svg
keywords:
  - kubernetes
  - homepage
  - dashboard
  - service-discovery
sources:
  - https://github.com/gethomepage/homepage
