{{- if and .Values.dispatcharr.enabled .Values.dispatcharr.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-dispatcharr
  labels:
    app.kubernetes.io/name: dispatcharr
    app.kubernetes.io/instance: {{ .Release.Name }}-dispatcharr
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
  {{- with .Values.dispatcharr.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.dispatcharr.ingress.className }}
  ingressClassName: {{ .Values.dispatcharr.ingress.className }}
  {{- end }}
  {{- if .Values.dispatcharr.ingress.tls }}
  tls:
    {{- range .Values.dispatcharr.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.dispatcharr.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: dispatcharr
                port:
                  number: {{ $.Values.dispatcharr.service.dispatcharr.port | default 9191 }}
          {{- end }}
    {{- end }}
{{- end }}
