{{- if and .Values.dispatcharr.enabled .Values.dispatcharr.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.dispatcharr.serviceAccount.name | default (printf "%s-dispatcharr" .Release.Name) }}
  labels:
    app.kubernetes.io/name: dispatcharr
    app.kubernetes.io/instance: {{ .Release.Name }}-dispatcharr
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
  {{- with .Values.dispatcharr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
