{{- if and .Values.sonarr.enabled (or (eq .Values.sonarr.database.mode "external") (eq .Values.sonarr.database.mode "cluster")) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sonarr-config
  labels:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/instance: {{ .Release.Name }}-sonarr
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
data:
  db-config.xml: |
    {{- if eq .Values.sonarr.database.mode "cluster" }}
    <PostgresUser>{{ .Values.sonarr.database.auth.username | default "sonarr" }}</PostgresUser>
    <PostgresPassword>__DB_PASSWORD__</PostgresPassword>
    <PostgresHost>{{ .Values.sonarr.database.cluster.name | default (printf "%s-sonarr-db" .Release.Name) }}-rw</PostgresHost>
    <PostgresPort>{{ .Values.sonarr.database.external.port }}</PostgresPort>
    {{- else }}
    <PostgresUser>{{ required "sonarr.database.auth.username is required when sonarr.database.mode is 'external'" .Values.sonarr.database.auth.username }}</PostgresUser>
    <PostgresPassword>__DB_PASSWORD__</PostgresPassword>
    <PostgresHost>{{ required "sonarr.database.external.host is required when sonarr.database.mode is 'external'" .Values.sonarr.database.external.host }}</PostgresHost>
    <PostgresPort>{{ .Values.sonarr.database.external.port }}</PostgresPort>
    {{- end }}
    <PostgresMainDb>{{ .Values.sonarr.database.external.mainDatabase }}</PostgresMainDb>
    <PostgresLogDb>{{ .Values.sonarr.database.external.logDatabase }}</PostgresLogDb>
{{- end }}
