{{- if and .Values.sonarr.enabled (or (eq .Values.sonarr.database.mode "external") (eq .Values.sonarr.database.mode "cluster")) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sonarr-config
  labels:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/instance: {{ .Release.Name }}-sonarr
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
data:
  config.xml: |
    <Config>
      <BindAddress>*</BindAddress>
      <Port>8989</Port>
      <SslPort>9898</SslPort>
      <EnableSsl>False</EnableSsl>
      <LaunchBrowser>True</LaunchBrowser>
      <AuthenticationMethod>External</AuthenticationMethod>
      <AuthenticationRequired>DisabledForLocalAddresses</AuthenticationRequired>
      <Branch>main</Branch>
      <LogLevel>info</LogLevel>
      <SslCertPath></SslCertPath>
      <SslCertPassword></SslCertPassword>
      <UrlBase></UrlBase>
      <InstanceName>Sonarr</InstanceName>
      <UpdateMechanism>Docker</UpdateMechanism>
      {{- if eq .Values.sonarr.database.mode "cluster" }}
      <PostgresUser>sonarr</PostgresUser>
      <PostgresPassword>__DB_PASSWORD__</PostgresPassword>
      <PostgresHost>{{ .Release.Name }}-sonarr-db-rw</PostgresHost>
      <PostgresPort>5432</PostgresPort>
      {{- else }}
      <PostgresUser>{{ required "sonarr.database.username is required when sonarr.database.mode is 'external'" .Values.sonarr.database.username }}</PostgresUser>
      <PostgresPassword>__DB_PASSWORD__</PostgresPassword>
      <PostgresHost>{{ required "sonarr.database.host is required when sonarr.database.mode is 'external'" .Values.sonarr.database.host }}</PostgresHost>
      <PostgresPort>{{ .Values.sonarr.database.port }}</PostgresPort>
      {{- end }}
      <PostgresMainDb>{{ .Values.sonarr.database.mainDatabase }}</PostgresMainDb>
      <PostgresLogDb>{{ .Values.sonarr.database.logDatabase }}</PostgresLogDb>
    </Config>
{{- end }}
