## Default values for Kubernetes Cloudflare DDNS

## @section Image parameters

## @param image.repository The Docker repository to pull the image from.
## @param image.tag The image tag to use.
## @param image.autoupdate.enabled Enable automatic image updates via ArgoCD Image Updater.
## @param image.autoupdate.strategy Strategy for image updates (semver, latest, newest-build, name, alphabetical, digest).
## @param image.autoupdate.allowTags Match function for allowed tags (e.g., "regexp:^[0-9]+\\.[0-9]+\\.[0-9]+$" or "any").
## @param image.autoupdate.ignoreTags List of glob patterns to ignore specific tags.
## @param image.autoupdate.pullSecret Reference to secret for private registry authentication.
## @param image.autoupdate.platforms List of target platforms (e.g., ["linux/amd64", "linux/arm64"]).
##
image:
  repository: raulpatel/kubernetes-cloudflare-ddns
  tag: "1.0.1"
  autoupdate:
    enabled: false
    strategy: ""
    allowTags: ""
    ignoreTags: []
    pullSecret: ""
    platforms: []

## @section Cron parameters

## @param cron.job.schedule Interval for how often the job should run.
## @param cron.job.successfulJobsHistoryLimit Limit of the successful jobs saved in history as completed pods.
## @param cron.pod.restartPolicy The logic for restarting the cron pod.
##
cron:
  job:
    schedule: '"*/5 * * * *"'
    successfulJobsHistoryLimit: 1

  pod:
    restartPolicy: OnFailure

## @section Secret parameters

## @param secret.existingSecret Name of an existing secret. Check [secret.yaml](https://artifacthub.io/packages/helm/raulpatel/kubernetes-cloudflare-ddns?modal=template&template=secret.yaml) for the required variables.
## @param secret.authKey The value of your Cloudflare API Key.
## @param secret.dnsRecord The A record you want to update.
## @param secret.recordId The ID of the record you are updating.
## @param secret.zoneId The zone ID of your domain.
##
secret:
  existingSecret: ""
  authKey: ""
  dnsRecord: ""
  recordId: ""
  zoneId: ""


## @section ArgoCD Image Updater parameters

## @param imageUpdater.namespace Namespace where the ImageUpdater CRD will be created.
## @param imageUpdater.argocdNamespace Namespace where ArgoCD Applications are located.
## @param imageUpdater.applicationName Name or pattern of the ArgoCD Application to update. Defaults to Release name.
## @param imageUpdater.imageAlias Alias for the image in the ImageUpdater CRD. Defaults to Release name.
## @param imageUpdater.forceUpdate Force update even if image is not currently deployed.
## @param imageUpdater.helm Helm-specific configuration for parameter names (e.g., {name: "image.repository", tag: "image.tag"}).
## @param imageUpdater.kustomize Kustomize-specific configuration (e.g., {name: "original/image"}).
## @param imageUpdater.writeBackConfig Write-back configuration for GitOps.
##
imageUpdater:
  namespace: argocd
  argocdNamespace: argocd
  applicationName: ""
  imageAlias: ""
  forceUpdate: false
  helm: {}
  kustomize: {}
  writeBackConfig: {}
