## Default values for Kubernetes Cloudflare DDNS

## @section Image parameters

## @param image.repository The Docker repository to pull the image from.
## @param image.tag The image tag to use.
##
image:
  repository: raulpatel/kubernetes-cloudflare-ddns
  tag: "1.0.1"

## @section Cron parameters

## @param cron.job.schedule Interval for how often the job should run.
## @param cron.job.successfulJobsHistoryLimit Limit of the successful jobs saved in history as completed pods.
## @param cron.pod.restartPolicy The logic for restarting the cron pod.
##
cron:
  job:
    schedule: '"*/5 * * * *"'
    successfulJobsHistoryLimit: 1

  pod:
    restartPolicy: OnFailure

## @section Secret parameters

## @param secret.existingSecret Name of an existing secret. Check [secret.yaml](https://artifacthub.io/packages/helm/raulpatel/kubernetes-cloudflare-ddns?modal=template&template=secret.yaml) for the required variables.
## @param secret.authKey The value of your Cloudflare API Key.
## @param secret.dnsRecord The A record you want to update.
## @param secret.recordId The ID of the record you are updating.
## @param secret.zoneId The zone ID of your domain.
##
secret:
  existingSecret: ""
  authKey: ""
  dnsRecord: ""
  recordId: ""
  zoneId: ""

## @section ArgoCD Image Updater parameters

## @param imageUpdater.enabled Enable ArgoCD Image Updater integration. Creates a ConfigMap with annotations for automatic image updates.
## @param imageUpdater.updateStrategy Strategy for image updates (semver, latest, name, digest).
## @param imageUpdater.allowTags Regular expression to allow specific image tags (e.g., "regexp:^[0-9]+\\.[0-9]+\\.[0-9]+$" for semver only).
## @param imageUpdater.ignoreTags Regular expression to ignore specific image tags (e.g., "regexp:^.*-beta$" to ignore beta tags).
## @param imageUpdater.pullSecret Name of the secret containing credentials for pulling images from private registries.
## @param imageUpdater.extraAnnotations Additional custom annotations for ArgoCD Image Updater.
##
imageUpdater:
  enabled: false
  updateStrategy: semver
  allowTags: ""
  ignoreTags: ""
  pullSecret: ""
  extraAnnotations: {}
