{{- $fullName := include "immich.fullname" . -}}
{{- if and .Values.persistence.library.enabled (not .Values.persistence.library.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-library
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
    app.kubernetes.io/pvc-type: config
spec:
  accessModes:
    - {{ .Values.persistence.library.accessMode | quote }}
  {{- if .Values.persistence.library.storageClass }}
  storageClassName: {{ .Values.persistence.library.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.library.size | quote }}
{{- end }}
---
{{- if and .Values.machineLearning.enabled .Values.machineLearning.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-ml-cache
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/pvc-type: ml-cache
    app.kubernetes.io/component: machine-learning
spec:
  accessModes:
    - {{ .Values.machineLearning.persistence.accessMode | quote }}
  {{- if .Values.machineLearning.persistence.storageClass }}
  storageClassName: {{ .Values.machineLearning.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.machineLearning.persistence.size | quote }}
{{- end }}
