{{- $fullName := include "immich.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-server
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "immich.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
