{{- if and .Values.velero.enabled (or .Values.persistence.library.enabled (and .Values.database.backup.enabled .Values.database.backup.persistence.enabled)) }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ include "immich.fullname" . }}
  namespace: {{ .Values.velero.namespace | default "velero" }}
  {{- with .Values.velero.annotations }}
  annotations:
    {{- toYaml . | nindent 6 }}
  {{- end }}
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    velero.io/backup-schedule: {{ include "immich.fullname" . }}
spec:
  schedule: {{ .Values.velero.schedule | quote }}
  template:
    includedNamespaces:
      - {{ .Release.Namespace }}
    includedResources:
      - "*"
    ttl: {{ .Values.velero.ttl }}
    {{- if .Values.velero.includeClusterResources }}
    includeClusterResources: {{ .Values.velero.includeClusterResources }}
    {{- end }}
    {{- if .Values.velero.snapshotVolumes }}
    snapshotVolumes: {{ .Values.velero.snapshotVolumes }}
    {{- end }}
    {{- if .Values.velero.defaultVolumesToFsBackup }}
    defaultVolumesToFsBackup: {{ .Values.velero.defaultVolumesToFsBackup }}
    {{- end }}
    {{- if .Values.velero.storageLocation }}
    storageLocation: {{ .Values.velero.storageLocation }}
    {{- end }}
    {{- if .Values.velero.volumeSnapshotLocations }}
    volumeSnapshotLocations:
      {{- toYaml .Values.velero.volumeSnapshotLocations | nindent 6 }}
    {{- end }}
    metadata:
      labels:
        {{- include "immich.labels" . | nindent 8 }}
        velero.io/backup-type: scheduled
        velero.io/pvc-target: config
{{- end }}
