{{- if .Values.radarr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-radarr
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: {{ .Release.Name }}-radarr
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  {{- if not .Values.radarr.autoscaling.enabled }}
  replicas: {{ .Values.radarr.replicaCount }}
  {{- end }}
  strategy:
    {{- .Values.radarr.deployment.strategy | toYaml | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
      app.kubernetes.io/instance: {{ .Release.Name }}-radarr
  template:
    metadata:
      {{- with .Values.radarr.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: radarr
        app.kubernetes.io/instance: {{ .Release.Name }}-radarr
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/part-of: {{ .Release.Name | quote }}
    spec:
      {{- with .Values.radarr.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.radarr.serviceAccount.name | default (printf "%s-radarr" .Release.Name) }}
      securityContext:
        {{- toYaml .Values.radarr.podSecurityContext | nindent 8 }}
      {{- if or (and .Values.media.enabled .Values.radarr.persistence.enabled) (eq .Values.radarr.database.mode "external") .Values.radarr.initContainers }}
      initContainers:
        {{- if and .Values.media.enabled .Values.radarr.persistence.enabled }}
        - name: init-directories
          image: busybox
          command: ['sh', '-c', 'mkdir -p /media/{{ .Values.media.paths.movies }} /media/{{ .Values.media.paths.downloads }} && chown -R 1000:1000 /media/{{ .Values.media.paths.movies }} /media/{{ .Values.media.paths.downloads }}']
          volumeMounts:
            - name: media
              mountPath: /media
        {{- end }}
        {{- if eq .Values.radarr.database.mode "external" }}
        - name: init-config
          image: busybox
          command:
            - sh
            - -c
            - |
              cp /config-template/config.xml /config/config.xml
              sed -i "s/__DB_PASSWORD__/${DB_PASSWORD}/g" /config/config.xml
              chown 1000:1000 /config/config.xml
          env:
            {{- if .Values.radarr.database.existingSecret }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.radarr.database.existingSecret }}
                  key: password
            {{- else }}
            - name: DB_PASSWORD
              value: {{ .Values.radarr.database.password | quote }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: config-template
              mountPath: /config-template
        {{- end }}
        {{- if .Values.radarr.initContainers }}
        {{- toYaml .Values.radarr.initContainers | nindent 8 }}
        {{- end }}
      {{- end }}
      volumes:
        - name: config
          {{- if .Values.radarr.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.radarr.persistence.existingClaim | default (printf "%s-radarr" .Release.Name) }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if eq .Values.radarr.database.mode "external" }}
        - name: config-template
          configMap:
            name: {{ .Release.Name }}-radarr-config
        {{- end }}
        {{- if .Values.radarr.persistence.cache.enabled }}
        - name: cache
          emptyDir:
            {{- if .Values.radarr.persistence.cache.size }}
            sizeLimit: {{ .Values.radarr.persistence.cache.size }}
            {{- end }}
        {{- end }}
        - name: media
          {{- if and .Values.media.enabled .Values.radarr.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.media.existingClaim }}{{ .Values.media.existingClaim }}{{- else }}{{ .Release.Name }}-media{{- end }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if .Values.radarr.persistence.additionalVolumes }}
          {{- .Values.radarr.persistence.additionalVolumes | toYaml | nindent 8}}
        {{- if .Values.radarr.persistence.backup.enabled }}
        - name: backup
          persistentVolumeClaim:
            claimName: {{ .Values.radarr.persistence.backup.existingClaim | default (printf "%s-radarr-backup" .Release.Name) }}
        {{- end }}
        {{- end }}
      containers:
        - name: radarr
          securityContext:
            {{- toYaml .Values.radarr.securityContext | nindent 12 }}
          image: "{{ .Values.radarr.image.repository }}:{{ .Values.radarr.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.radarr.image.pullPolicy }}
          volumeMounts:
            - mountPath: /config
              name: config
            {{- if .Values.radarr.persistence.backup.enabled }}
            - mountPath: /config/backups
              name: backup
            {{- end }}
            {{- if .Values.radarr.persistence.cache.enabled }}
            - mountPath: /config/cache
              name: cache
            {{- end }}
          {{- if and .Values.media.enabled .Values.radarr.persistence.enabled }}
            - mountPath: /media
              name: media
          {{- end }}
          {{- if .Values.radarr.persistence.additionalMounts }}
            {{- .Values.radarr.persistence.additionalMounts | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 7878
              protocol: TCP
          env:
            {{- range $k,$v := .Values.radarr.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            failureThreshold: 12
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /ping
              port: http
            failureThreshold: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.radarr.resources | nindent 12 }}
      {{- if .Values.radarr.runtimeClassName }}
      runtimeClassName: {{ .Values.radarr.runtimeClassName | quote }}
      {{- end }}
      {{- with .Values.radarr.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.radarr.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.radarr.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
