{{- if ne .Values.postgres.mode "external" }}
{{- if not .Values.postgres.secret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authentik.postgresql.secretName" . }}
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgres.password }}
  {{ .Values.postgres.secret.passwordKey }}: {{ .Values.postgres.password | quote }}
  {{- else }}
  {{ .Values.postgres.secret.passwordKey }}: {{ randAlphaNum 32 | quote }}
  {{- end }}
{{- end }}
{{- end }}
