{{- if and .Values.n8n.persistence.enabled (not .Values.n8n.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "n8n.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    velero.io/pvc-type: config
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.n8n.persistence.storageClass }}
  storageClassName: {{ .Values.n8n.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.n8n.persistence.size }}
{{- end }}
