{{- if eq .Values.database.mode "cluster" }}
{{- if .Values.database.cluster.secret.create }}
{{- $secretName := .Values.database.cluster.secret.name | default (printf "%s-n8n-db-app" .Release.Name) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $password := "" }}
{{- if $existingSecret }}
{{- $password = index $existingSecret.data "password" | b64dec }}
{{- else }}
{{- $password = .Values.database.cluster.secret.password | default (randAlphaNum 32) }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.database.cluster.secret.username }}
  password: {{ $password }}
{{- end }}

{{- if .Values.database.cluster.superuserSecret.create }}
{{- $superuserSecretName := .Values.database.cluster.superuserSecret.name | default (printf "%s-n8n-db-superuser" .Release.Name) }}
{{- $existingSuperuserSecret := lookup "v1" "Secret" .Release.Namespace $superuserSecretName }}
{{- $superuserPassword := "" }}
{{- if $existingSuperuserSecret }}
{{- $superuserPassword = index $existingSuperuserSecret.data "password" | b64dec }}
{{- else }}
{{- $superuserPassword = .Values.database.cluster.superuserSecret.password | default (randAlphaNum 32) }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $superuserSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.database.cluster.superuserSecret.username }}
  password: {{ $superuserPassword }}
{{- end }}
{{- end }}
