name: outline
maintainers:
  - name: raulpatel
    url: https://raulpatel.com
apiVersion: v2
appVersion: 0.87.4
version: 1.3.3
description: Raul Outline Wiki Helm Chart
home: https://github.com/FeLiNa22/homeserver/tree/main/charts/outline
icon: https://raulpatel.com/images/raul.svg
keywords:
  - kubernetes
  - outline
  - wiki
  - docs
sources:
  - https://github.com/outline/outline

dependencies:
  - condition: global.minioEnabled
    name: minio
    repository: https://charts.bitnami.com/bitnami
    version: 12.x.x
