{{- if and .Values.seerr.enabled (eq .Values.seerr.database.mode "cluster") .Values.seerr.database.auth.password (not .Values.seerr.database.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-seerr-db-secret
  labels:
    app.kubernetes.io/name: seerr-db
    app.kubernetes.io/instance: {{ .Release.Name }}-seerr-db
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.seerr.database.auth.username | default "seerr" }}
  password: {{ .Values.seerr.database.auth.password }}
{{- end }}
