{{- if and .Values.seerr.enabled .Values.seerr.persistence.enabled (not .Values.seerr.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-seerr
  labels:
    app.kubernetes.io/name: seerr
    app.kubernetes.io/instance: {{ .Release.Name }}-seerr
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
    velero.io/pvc-type: config
  {{- with .Values.seerr.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.seerr.persistence.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.seerr.persistence.volumeName }}
  volumeName: {{ .Values.seerr.persistence.volumeName }}
  {{- end }}
  {{- with .Values.seerr.persistence.storageClass }}
  storageClassName: {{ if (eq "-" .) }}""{{ else }}{{ . }}{{ end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.seerr.persistence.size | quote }}
{{- end }}

---
{{- if and .Values.seerr.enabled .Values.seerr.persistence.backup.enabled (not .Values.seerr.persistence.backup.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-seerr-backup
    velero.io/pvc-type: backup
  labels:
    app.kubernetes.io/name: seerr
    app.kubernetes.io/instance: {{ .Release.Name }}-seerr
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  accessModes:
    - {{ .Values.seerr.persistence.backup.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.seerr.persistence.backup.size | quote }}
  {{- if .Values.seerr.persistence.backup.storageClass }}
  storageClassName: {{ .Values.seerr.persistence.backup.storageClass | quote }}
  {{- end }}
{{- end }}
