{{- if and .Values.seerr.enabled (eq .Values.seerr.database.mode "external") (not .Values.seerr.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-seerr-db
  labels:
    app.kubernetes.io/name: seerr
    app.kubernetes.io/instance: {{ .Release.Name }}-seerr
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
type: Opaque
data:
  password: {{ required "seerr.database.password is required when seerr.database.mode is 'external' and seerr.database.existingSecret is not provided" .Values.seerr.database.password | b64enc | quote }}
{{- end }}
