{{- if and .Values.prowlarr.enabled (eq .Values.prowlarr.database.mode "cluster") }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.prowlarr.database.cluster.name | default (printf "%s-prowlarr-db" .Release.Name) }}
  labels:
    app.kubernetes.io/name: prowlarr-db
    app.kubernetes.io/instance: {{ .Release.Name }}-prowlarr-db
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  instances: {{ .Values.prowlarr.database.cluster.instances }}
  {{- if .Values.prowlarr.database.cluster.image }}
  imageName: {{ .Values.prowlarr.database.cluster.image.repository }}:{{ .Values.prowlarr.database.cluster.image.tag }}
  {{- end }}
  bootstrap:
    initdb:
      database: {{ .Values.prowlarr.database.external.mainDatabase }}
      owner: {{ .Values.prowlarr.database.auth.username | default "prowlarr" }}
      {{- if or .Values.prowlarr.database.auth.existingSecret .Values.prowlarr.database.auth.password }}
      secret:
        name: {{ .Values.prowlarr.database.auth.existingSecret | default (printf "%s-prowlarr-db-secret" .Release.Name) }}
      {{- end }}
      {{- if .Values.prowlarr.database.initSQL }}
      postInitSQL:
        {{- range .Values.prowlarr.database.initSQL }}
        - {{ . | quote }}
        {{- end }}
        - CREATE DATABASE "{{ .Values.prowlarr.database.external.logDatabase }}" OWNER {{ .Values.prowlarr.database.auth.username | default "prowlarr" }};
      {{- else }}
      postInitSQL:
        - CREATE DATABASE "{{ .Values.prowlarr.database.external.logDatabase }}" OWNER {{ .Values.prowlarr.database.auth.username | default "prowlarr" }};
      {{- end }}
  storage:
    {{- if .Values.prowlarr.database.persistence.storageClass }}
    storageClass: {{ .Values.prowlarr.database.persistence.storageClass }}
    {{- end }}
    size: {{ .Values.prowlarr.database.persistence.size }}
{{- end }}
