{{- if and .Values.velero.enabled .Values.prowlarr.enabled (or .Values.prowlarr.persistence.enabled .Values.prowlarr.persistence.backup.enabled) }}
{{- $pvcType := "" }}
{{- if .Values.prowlarr.persistence.backup.enabled }}
{{- $pvcType = "backup" }}
{{- else if .Values.prowlarr.persistence.enabled }}
{{- $pvcType = "config" }}
{{- end }}
{{- if $pvcType }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ .Release.Name }}-prowlarr
  {{- with .Values.velero.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: prowlarr
    app.kubernetes.io/instance: {{ .Release.Name }}-prowlarr
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
    velero.io/backup-schedule: {{ .Release.Name }}-prowlarr
spec:
  schedule: {{ .Values.velero.schedule | quote }}
  template:
    includedNamespaces:
      - {{ .Release.Namespace }}
    includedResources:
      - persistentvolumeclaims
      - persistentvolumes
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: prowlarr
        app.kubernetes.io/instance: {{ .Release.Name }}-prowlarr
        velero.io/pvc-type: {{ $pvcType }}
    {{- if .Values.velero.labelSelector }}
    {{- with .Values.velero.labelSelector }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
    ttl: {{ .Values.velero.ttl }}
    {{- if .Values.velero.includeClusterResources }}
    includeClusterResources: {{ .Values.velero.includeClusterResources }}
    {{- end }}
    {{- if .Values.velero.snapshotVolumes }}
    snapshotVolumes: {{ .Values.velero.snapshotVolumes }}
    {{- end }}
    {{- if .Values.velero.defaultVolumesToFsBackup }}
    defaultVolumesToFsBackup: {{ .Values.velero.defaultVolumesToFsBackup }}
    {{- end }}
    {{- if .Values.velero.storageLocation }}
    storageLocation: {{ .Values.velero.storageLocation }}
    {{- end }}
    {{- if .Values.velero.volumeSnapshotLocations }}
    volumeSnapshotLocations:
      {{- toYaml .Values.velero.volumeSnapshotLocations | nindent 6 }}
    {{- end }}
    metadata:
      labels:
        app.kubernetes.io/name: prowlarr
        app.kubernetes.io/instance: {{ .Release.Name }}-prowlarr
        velero.io/backup-type: scheduled
        velero.io/service: prowlarr
        velero.io/pvc-target: {{ $pvcType }}
{{- end }}
{{- end }}
