{{- if .Values.acestream.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-acestream-http
  labels:
    app.kubernetes.io/name: acestream
    app.kubernetes.io/instance: {{ .Release.Name }}-acestream
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
    app.kubernetes.io/component: http
spec:
  type: {{ .Values.acestream.service.http.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.acestream.service.http.port | default 6878 }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if (and (eq .Values.acestream.service.http.type "NodePort") (not (empty .Values.acestream.service.http.nodePort))) }}
      nodePort: {{ .Values.acestream.service.http.nodePort }}
  {{- end }}
  selector:
    app.kubernetes.io/name: acestream
    app.kubernetes.io/instance: {{ .Release.Name }}-acestream

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-acestream-udp
  labels:
    app.kubernetes.io/name: acestream
    app.kubernetes.io/instance: {{ .Release.Name }}-acestream
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
    app.kubernetes.io/component: udp
spec:
  type: {{ .Values.acestream.service.udp.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.acestream.service.udp.port | default 8621 }}
      targetPort: udp
      protocol: UDP
      name: udp
  {{- if (and (eq .Values.acestream.service.udp.type "NodePort") (not (empty .Values.acestream.service.udp.nodePort))) }}
      nodePort: {{ .Values.acestream.service.udp.nodePort }}
  {{- end }}
  selector:
    app.kubernetes.io/name: acestream
    app.kubernetes.io/instance: {{ .Release.Name }}-acestream

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-acestream-dispatcharr
  labels:
    app.kubernetes.io/name: acestream
    app.kubernetes.io/instance: {{ .Release.Name }}-acestream
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
    app.kubernetes.io/component: dispatcharr
spec:
  type: {{ .Values.acestream.service.dispatcharr.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.acestream.service.dispatcharr.port | default 9191 }}
      targetPort: dispatcharr
      protocol: TCP
      name: dispatcharr
  {{- if (and (eq .Values.acestream.service.dispatcharr.type "NodePort") (not (empty .Values.acestream.service.dispatcharr.nodePort))) }}
      nodePort: {{ .Values.acestream.service.dispatcharr.nodePort }}
  {{- end }}
  selector:
    app.kubernetes.io/name: acestream
    app.kubernetes.io/instance: {{ .Release.Name }}-acestream
{{- end }}
{{- if and .Values.acestream.enabled .Values.acestream.gluetun.enabled .Values.acestream.gluetun.httpProxy.enabled }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-acestream-gluetun-http
  labels:
    app.kubernetes.io/name: acestream
    app.kubernetes.io/instance: {{ .Release.Name }}-acestream
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
    app.kubernetes.io/component: http-proxy
spec:
  type: {{ .Values.acestream.gluetun.httpProxy.type | default "LoadBalancer" }}
  ports:
    - port: {{ .Values.acestream.gluetun.httpProxy.port | default 8888 }}
      targetPort: http-proxy
      protocol: TCP
      name: http-proxy
  selector:
    app.kubernetes.io/name: acestream
    app.kubernetes.io/instance: {{ .Release.Name }}-acestream
{{- end }}
{{- if and .Values.acestream.enabled .Values.acestream.gluetun.enabled .Values.acestream.gluetun.shadowsocksProxy.enabled }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-acestream-gluetun-shadowsocks
  labels:
    app.kubernetes.io/name: acestream
    app.kubernetes.io/instance: {{ .Release.Name }}-acestream
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
    app.kubernetes.io/component: shadowsocks
spec:
  type: {{ .Values.acestream.gluetun.shadowsocksProxy.type | default "LoadBalancer" }}
  ports:
    - port: {{ .Values.acestream.gluetun.shadowsocksProxy.port | default 8388 }}
      targetPort: shadowsocks-tcp
      protocol: TCP
      name: shadowsocks-tcp
    - port: {{ .Values.acestream.gluetun.shadowsocksProxy.port | default 8388 }}
      targetPort: shadowsocks-udp
      protocol: UDP
      name: shadowsocks-udp
  selector:
    app.kubernetes.io/name: acestream
    app.kubernetes.io/instance: {{ .Release.Name }}-acestream
{{- end }}
