{{- if and .Values.qbittorrent.enabled .Values.qbittorrent.persistence.enabled (not .Values.qbittorrent.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-qbittorrent
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: {{ .Release.Name }}-qbittorrent
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
  {{- if .Values.qbittorrent.persistence.annotations }}
  annotations:
    {{- toYaml .Values.qbittorrent.persistence.annotations | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.qbittorrent.persistence.accessMode | quote }}
  {{- if .Values.qbittorrent.persistence.storageClass }}
  storageClassName: {{ .Values.qbittorrent.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.qbittorrent.persistence.size | quote }}
{{- end }}

---
{{- if and .Values.qbittorrent.enabled .Values.qbittorrent.persistence.backup.enabled (not .Values.qbittorrent.persistence.backup.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-qbittorrent-backup
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: {{ .Release.Name }}-qbittorrent
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  accessModes:
    - {{ .Values.qbittorrent.persistence.backup.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.qbittorrent.persistence.backup.size | quote }}
  {{- if .Values.qbittorrent.persistence.backup.storageClass }}
  storageClassName: {{ .Values.qbittorrent.persistence.backup.storageClass | quote }}
  {{- end }}
{{- end }}

---
{{- if and .Values.qbittorrent.enabled .Values.qbittorrent.persistence.downloads.enabled (not .Values.qbittorrent.persistence.downloads.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-qbittorrent-downloads
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: {{ .Release.Name }}-qbittorrent
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  accessModes:
    - {{ .Values.qbittorrent.persistence.downloads.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.qbittorrent.persistence.downloads.size | quote }}
  {{- if .Values.qbittorrent.persistence.downloads.storageClass }}
  storageClassName: {{ .Values.qbittorrent.persistence.downloads.storageClass | quote }}
  {{- end }}
{{- end }}
