{{- if .Values.qbittorrent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-qbittorrent-web
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: {{ .Release.Name }}-qbittorrent
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  type: {{ .Values.qbittorrent.service.web.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.qbittorrent.service.web.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if (and (eq .Values.qbittorrent.service.web.type "NodePort") (not (empty .Values.qbittorrent.service.web.nodePort))) }}
      nodePort: {{ .Values.qbittorrent.service.web.nodePort }}
  {{- end }}
  selector:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: {{ .Release.Name }}-qbittorrent

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-qbittorrent-bt
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: {{ .Release.Name }}-qbittorrent
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  type: {{ .Values.qbittorrent.service.bt.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.qbittorrent.service.bt.port | default 6881 }}
      targetPort: bittorrent-tcp
      protocol: TCP
      name: bittorrent-tcp
  {{- if (and (eq .Values.qbittorrent.service.bt.type "NodePort") (not (empty .Values.qbittorrent.service.bt.nodePort))) }}
      nodePort: {{ .Values.qbittorrent.service.bt.nodePort }}
  {{- end }}
    - port: {{ .Values.qbittorrent.service.bt.port | default 6881 }}
      targetPort: bittorrent-udp
      protocol: UDP
      name: bittorrent-udp
  {{- if (and (eq .Values.qbittorrent.service.bt.type "NodePort") (not (empty .Values.qbittorrent.service.bt.nodePort))) }}
      nodePort: {{ .Values.qbittorrent.service.bt.nodePort }}
  {{- end }}
  selector:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: {{ .Release.Name }}-qbittorrent
{{- end }}
{{- if and .Values.qbittorrent.enabled .Values.qbittorrent.gluetun.enabled .Values.qbittorrent.gluetun.httpProxy.enabled }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gluetun-http
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: {{ .Release.Name }}-qbittorrent
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
    app.kubernetes.io/component: http-proxy
spec:
  type: {{ .Values.qbittorrent.gluetun.httpProxy.type | default "LoadBalancer" }}
  ports:
    - port: {{ .Values.qbittorrent.gluetun.httpProxy.port }}
      targetPort: http-proxy
      protocol: TCP
      name: http-proxy
  selector:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: {{ .Release.Name }}-qbittorrent
{{- end }}
{{- if and .Values.qbittorrent.enabled .Values.qbittorrent.gluetun.enabled .Values.qbittorrent.gluetun.shadowsocksProxy.enabled }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gluetun-shadowsocks
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: {{ .Release.Name }}-qbittorrent
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
    app.kubernetes.io/component: shadowsocks
spec:
  type: {{ .Values.qbittorrent.gluetun.shadowsocksProxy.type | default "LoadBalancer" }}
  ports:
    - port: {{ .Values.qbittorrent.gluetun.shadowsocksProxy.port }}
      targetPort: shadowsocks
      protocol: TCP
      name: shadowsocks
  selector:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: {{ .Release.Name }}-qbittorrent
{{- end }}
