{{- if and .Values.sabnzbd.enabled .Values.sabnzbd.persistence.enabled (not .Values.sabnzbd.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-sabnzbd
  labels:
    app.kubernetes.io/name: sabnzbd
    app.kubernetes.io/instance: {{ .Release.Name }}-sabnzbd
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
    velero.io/pvc-type: config
  {{- if .Values.sabnzbd.persistence.annotations }}
  annotations:
    {{- toYaml .Values.sabnzbd.persistence.annotations | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.sabnzbd.persistence.accessMode | quote }}
  {{- if .Values.sabnzbd.persistence.storageClass }}
  storageClassName: {{ .Values.sabnzbd.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.sabnzbd.persistence.size | quote }}
{{- end }}

---
{{- if and .Values.sabnzbd.enabled .Values.sabnzbd.persistence.backup.enabled (not .Values.sabnzbd.persistence.backup.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-sabnzbd-backup
  labels:
    app.kubernetes.io/name: sabnzbd
    app.kubernetes.io/instance: {{ .Release.Name }}-sabnzbd
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    velero.io/pvc-type: backup
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  accessModes:
    - {{ .Values.sabnzbd.persistence.backup.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.sabnzbd.persistence.backup.size | quote }}
  {{- if .Values.sabnzbd.persistence.backup.storageClass }}
  storageClassName: {{ .Values.sabnzbd.persistence.backup.storageClass | quote }}
  {{- end }}
{{- end }}

---
{{- if and .Values.sabnzbd.enabled .Values.sabnzbd.persistence.downloads.enabled (not .Values.sabnzbd.persistence.downloads.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-sabnzbd-downloads
  labels:
    app.kubernetes.io/name: sabnzbd
    app.kubernetes.io/instance: {{ .Release.Name }}-sabnzbd
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  accessModes:
    - {{ .Values.sabnzbd.persistence.downloads.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.sabnzbd.persistence.downloads.size | quote }}
  {{- if .Values.sabnzbd.persistence.downloads.storageClass }}
  storageClassName: {{ .Values.sabnzbd.persistence.downloads.storageClass | quote }}
  {{- end }}
{{- end }}
