{{- if and .Values.velero.enabled .Values.sabnzbd.enabled .Values.sabnzbd.persistence.enabled }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ .Release.Name }}-sabnzbd
  {{- with .Values.velero.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: sabnzbd
    app.kubernetes.io/instance: {{ .Release.Name }}-sabnzbd
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
    velero.io/backup-schedule: {{ .Release.Name }}-sabnzbd
spec:
  schedule: {{ .Values.velero.schedule | quote }}
  template:
    includedNamespaces:
      - {{ .Release.Namespace }}
    includedResources:
      - persistentvolumeclaims
      - persistentvolumes
    labelSelector:
      matchExpressions:
        - key: app.kubernetes.io/instance
          operator: In
          values:
            - {{ .Release.Name }}-sabnzbd
        - key: app.kubernetes.io/name
          operator: In
          values:
            - sabnzbd
    {{- if .Values.velero.labelSelector }}
    {{- with .Values.velero.labelSelector }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
    ttl: {{ .Values.velero.ttl }}
    {{- if .Values.velero.includeClusterResources }}
    includeClusterResources: {{ .Values.velero.includeClusterResources }}
    {{- end }}
    {{- if .Values.velero.snapshotVolumes }}
    snapshotVolumes: {{ .Values.velero.snapshotVolumes }}
    {{- end }}
    {{- if .Values.velero.defaultVolumesToFsBackup }}
    defaultVolumesToFsBackup: {{ .Values.velero.defaultVolumesToFsBackup }}
    {{- end }}
    {{- if .Values.velero.storageLocation }}
    storageLocation: {{ .Values.velero.storageLocation }}
    {{- end }}
    {{- if .Values.velero.volumeSnapshotLocations }}
    volumeSnapshotLocations:
      {{- toYaml .Values.velero.volumeSnapshotLocations | nindent 6 }}
    {{- end }}
    metadata:
      labels:
        app.kubernetes.io/name: sabnzbd
        app.kubernetes.io/instance: {{ .Release.Name }}-sabnzbd
        velero.io/backup-type: scheduled
        velero.io/service: sabnzbd
{{- end }}
