{{- if and .Values.lidarr.enabled (eq .Values.lidarr.database.mode "cluster") .Values.lidarr.database.auth.password (not .Values.lidarr.database.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-lidarr-db-secret
  labels:
    app.kubernetes.io/name: lidarr-db
    app.kubernetes.io/instance: {{ .Release.Name }}-lidarr-db
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.lidarr.database.auth.username | default "lidarr" }}
  password: {{ .Values.lidarr.database.auth.password }}
{{- end }}
