apiVersion: v2
name: authentik
description: A Helm chart for authentik - an open-source Identity Provider focused on flexibility and versatility
type: application
version: 1.0.8
appVersion: "2025.12.4"
keywords:
  - authentik
  - authentication
  - identity
  - sso
  - saml
  - oauth
  - oidc
  - ldap
home: https://goauthentik.io
sources:
  - https://github.com/goauthentik/authentik
maintainers:
  - name: FeLiNa22
