name: n8n
maintainers:
  - name: raulpatel
    url: https://raulpatel.com
apiVersion: v2
appVersion: latest
version: 1.1.0
description: n8n workflow automation Helm Chart
home: https://github.com/FeLiNa22/helm/tree/main/charts/n8n
icon: https://n8n.io/favicon.ico
keywords:
  - kubernetes
  - n8n
  - workflow
  - automation
sources:
  - https://github.com/n8n-io/n8n
