name: nextcloud
maintainers:
  - name: raulpatel
    url: https://raulpatel.com
apiVersion: v2
appVersion: 32.0.3
version: 1.3.9
description: Nextcloud Helm Chart
type: application
home: https://github.com/FeLiNa22/homeserver/tree/main/charts/nextcloud
icon: https://raulpatel.com/images/raul.svg
keywords:
  - kubernetes
  - nextcloud
  - cloud
  - storage
sources:
  - https://github.com/nextcloud/server
