apiVersion: v2
name: immich
description: A Helm chart for Immich - High performance self-hosted photo and video management solution
type: application
version: 1.4.1
appVersion: "v2.4.1"
keywords:
  - immich
  - photos
  - videos
  - media
  - self-hosted
home: https://immich.app
sources:
  - https://github.com/immich-app/immich
maintainers:
  - name: FeLiNa22

dependencies:
  # PostgreSQL subchart (only used when postgresql.mode is 'standalone')
  - condition: postgresql.standalone.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 13.x.x
    alias: postgresql-standalone
