apiVersion: v2
name: immich
description: A Helm chart for Immich - High performance self-hosted photo and video management solution
type: application
version: 1.4.0
appVersion: "v2.4.1"
keywords:
  - immich
  - photos
  - videos
  - media
  - self-hosted
home: https://immich.app
sources:
  - https://github.com/immich-app/immich
maintainers:
  - name: FeLiNa22

dependencies:
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.x.x
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 13.x.x
