{{- if and .Values.velero.enabled (or .Values.persistence.enabled .Values.persistence.backup.enabled) }}
{{- $pvcType := "" }}
{{- if .Values.persistence.backup.enabled }}
{{- $pvcType = "backup" }}
{{- else if .Values.persistence.enabled }}
{{- $pvcType = "config" }}
{{- end }}
{{- if $pvcType }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.velero.namespace | default "velero" }}
  {{- with .Values.velero.annotations }}
  annotations:
    {{- toYaml . | nindent 6 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    velero.io/backup-schedule: {{ .Release.Name }}
spec:
  schedule: {{ .Values.velero.schedule | quote }}
  template:
    includedNamespaces:
      - {{ .Release.Namespace }}
    includedResources:
      - "*"
    ttl: {{ .Values.velero.ttl }}
    {{- if .Values.velero.includeClusterResources }}
    includeClusterResources: {{ .Values.velero.includeClusterResources }}
    {{- end }}
    {{- if .Values.velero.snapshotVolumes }}
    snapshotVolumes: {{ .Values.velero.snapshotVolumes }}
    {{- end }}
    {{- if .Values.velero.defaultVolumesToFsBackup }}
    defaultVolumesToFsBackup: {{ .Values.velero.defaultVolumesToFsBackup }}
    {{- end }}
    {{- if .Values.velero.storageLocation }}
    storageLocation: {{ .Values.velero.storageLocation }}
    {{- end }}
    {{- if .Values.velero.volumeSnapshotLocations }}
    volumeSnapshotLocations:
      {{- toYaml .Values.velero.volumeSnapshotLocations | nindent 6 }}
    {{- end }}
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        velero.io/backup-type: scheduled
        velero.io/pvc-target: {{ $pvcType }}
{{- end }}
{{- end }}
