{{- if .Values.enabled }}
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-service-discovery
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-service-discovery
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | default (printf "%s" .Release.Name) }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
