{{- if and .Values.enabled .Values.postgres.enabled }}
{{- $secretName := include "frigate.postgresql.secretName" . -}}

{{- if not .Values.postgres.password.secretName }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- if not $existingSecret }}
{{- $userPassword := randAlphaNum 32 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/name: frigate-database
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  password: {{ $userPassword }}
{{- end }}
{{- end }}

{{- if eq .Values.postgres.mode "cluster" }}
---
{{- $secretName := include "frigate.postgresql.secretName" . -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-frigate-db
  labels:
    app.kubernetes.io/name: frigate-database
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  instances: {{ .Values.postgres.cluster.instances }}
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover

  imageName: {{ .Values.postgres.cluster.image.repository }}:{{ .Values.postgres.cluster.image.tag }}

  bootstrap:
    initdb:
      database: {{ include "frigate.postgresql.database" . }}
      owner: {{ include "frigate.postgresql.username" . }}
      secret:
        name: {{ $secretName }}
      {{- if .Values.postgres.initSQL }}
      postInitSQL:
        {{- toYaml .Values.postgres.initSQL | nindent 8 }}
      {{- end }}

  storage:
    size: {{ .Values.postgres.cluster.persistence.size }}
    {{- if .Values.postgres.cluster.persistence.storageClass }}
    storageClass: {{ .Values.postgres.cluster.persistence.storageClass }}
    {{- end }}

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "1310kB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
    pg_hba:
      - host all all all scram-sha-256

  monitoring:
    enablePodMonitor: false

  {{- if .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml .Values.nodeSelector | nindent 4 }}
  {{- end }}

  {{- if .Values.tolerations }}
  tolerations:
    {{- toYaml .Values.tolerations | nindent 4 }}
  {{- end }}

  {{- if .Values.affinity }}
  affinity:
    {{- toYaml .Values.affinity | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
