{{- if and .Values.enabled .Values.database.enabled (eq .Values.database.mode "cluster") }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-{{ .Values.database.cluster.name }}
  labels:
    app.kubernetes.io/name: frigate-database
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  instances: {{ .Values.database.cluster.instances }}
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover

  imageName: {{ .Values.database.cluster.image.repository }}:{{ .Values.database.cluster.image.tag }}

  {{- if or .Values.database.cluster.superuserSecret.name .Values.database.cluster.superuserSecret.create }}
  superuserSecret:
    name: {{ .Values.database.cluster.superuserSecret.name | default (printf "%s-frigate-db-superuser" .Release.Name) }}
  {{- end }}

  bootstrap:
    initdb:
      database: {{ .Values.database.auth.username }}
      owner: {{ .Values.database.auth.username }}
      {{- if or .Values.database.cluster.secret.name .Values.database.cluster.secret.create }}
      secret:
        name: {{ .Values.database.cluster.secret.name | default (printf "%s-frigate-db-app" .Release.Name) }}
      {{- end }}
      {{- if .Values.database.initSQL }}
      postInitSQL:
        {{- range .Values.database.initSQL }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}

  storage:
    size: {{ .Values.database.persistence.size }}
    {{- if .Values.database.persistence.storageClass }}
    storageClass: {{ .Values.database.persistence.storageClass }}
    {{- end }}

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "1310kB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
    pg_hba:
      - host all all all scram-sha-256

  monitoring:
    enablePodMonitor: false

  {{- if .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml .Values.nodeSelector | nindent 4 }}
  {{- end }}

  {{- if .Values.tolerations }}
  tolerations:
    {{- toYaml .Values.tolerations | nindent 4 }}
  {{- end }}

  {{- if .Values.affinity }}
  affinity:
    {{- toYaml .Values.affinity | nindent 4 }}
  {{- end }}
{{- end }}
