{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 5000 }}
      targetPort: http
      protocol: TCP
      name: http
{{ if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{.Values.service.nodePort}}
{{ end }}
    - port: 8554
      targetPort: rtsp
      protocol: TCP
      name: rtsp
    - port: 8555
      targetPort: webrtc
      protocol: TCP
      name: webrtc
  selector:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
