{{- $fullName := include "outline.fullname" . -}}
{{- $secretName := include "outline.postgresql.secretName" . -}}

{{- if .Values.postgres.password.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: kubernetes.io/basic-auth
stringData:
  username: {{ include "outline.postgresql.username" . }}
  password: {{ .Values.postgres.password.value }}
{{- else if not .Values.postgres.password.secretName }}
{{- fail "Either postgres.password.value or postgres.password.secretName must be provided" }}
{{- end }}

{{- if eq .Values.postgres.mode "cluster" }}
---
{{- $fullName := include "outline.fullname" . -}}
{{- $secretName := include "outline.postgresql.secretName" . -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-postgres-cluster
  labels:
    {{- include "outline.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  instances: {{ .Values.postgres.cluster.instances }}
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover

  imageName: {{ .Values.postgres.cluster.image.repository }}:{{ .Values.postgres.cluster.image.tag }}

  bootstrap:
    initdb:
      database: {{ include "outline.postgresql.database" . }}
      owner: {{ include "outline.postgresql.username" . }}
      secret:
        name: {{ $secretName }}
      {{- if .Values.postgres.initSQL }}
      postInitSQL:
        {{- range .Values.postgres.initSQL }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}

  storage:
    {{- if .Values.postgres.cluster.persistence.existingClaim }}
    pvcTemplate:
      dataSource:
        name: {{ .Values.postgres.cluster.persistence.existingClaim }}
        kind: PersistentVolumeClaim
    {{- else }}
    size: {{ .Values.postgres.cluster.persistence.size }}
    {{- if .Values.postgres.cluster.persistence.storageClass }}
    storageClass: {{ .Values.postgres.cluster.persistence.storageClass }}
    {{- end }}
    {{- end }}

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "1310kB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
    pg_hba:
      - host all all all scram-sha-256

  monitoring:
    enablePodMonitor: false

  {{- if .Values.outline.nodeSelector }}
  nodeSelector:
    {{- toYaml .Values.outline.nodeSelector | nindent 4 }}
  {{- end }}

  {{- if .Values.outline.tolerations }}
  tolerations:
    {{- toYaml .Values.outline.tolerations | nindent 4 }}
  {{- end }}

  {{- if .Values.outline.affinity }}
  affinity:
    {{- toYaml .Values.outline.affinity | nindent 4 }}
  {{- end }}
{{- end }}
